version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python telegram_bot/main.py
    container_name: telegram_bot
    env_file: 
      - .env
    volumes:
      - .:/usr/src/telebot/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27019'
    volumes:
      - mongo_data:/data/db
    env_file:
      - db.env

volumes:
  mongo_data:
