version: '3.9'
services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python telegram_bot/main.py
    container_name: telegram_bot
    env_file: 
      - .env
    volumes:
      - .:/usr/src/telebot/
